//
// Created by Ruimin Zeng on 2/15/20.
//

#ifndef CS499_RAYMONDJUNE_EVENT_H
#define CS499_RAYMONDJUNE_EVENT_H

enum EVENT { REGISTER, WARBLE, FOLLOW, READ, PROFILE, STREAM };

#endif  // CS499_RAYMONDJUNE_EVENT_H
